# Generated by Django 2.2.3 on 2019-08-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('trigger_type', models.CharField(choices=[('email', 'email'), ('sms', 'sms'), ('all', 'all')], max_length=4)),
                ('canary_doc', models.FileField(upload_to='docs')),
                ('protocol', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('dns', models.NullBooleanField()),
                ('canary_filename', models.CharField(max_length=255)),
                ('directory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('canary_string', models.CharField(max_length=512)),
                ('dest', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('failed', 'failed'), ('completed', 'completed'), ('pending', 'pending')], max_length=9)),
                ('reason', models.CharField(max_length=4096)),
                ('canary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canary_files.CanaryItem')),
            ],
        ),
    ]
