# Generated by Django 2.2.3 on 2019-08-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanaryAlertItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('identifier', models.CharField(max_length=50)),
                ('canary_type', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=15)),
                ('node', models.CharField(blank=True, max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=250)),
                ('smb_loc', models.CharField(blank=True, max_length=50)),
                ('filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MimiAlertItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinename', models.CharField(max_length=50)),
                ('sid', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('md5', models.CharField(max_length=32)),
                ('sha1', models.CharField(max_length=40)),
                ('target', models.CharField(max_length=255)),
                ('accessMask', models.CharField(max_length=4)),
                ('stack', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='SampleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('sha1', models.CharField(max_length=40, unique=True)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('ssdeep', models.CharField(max_length=148)),
                ('sample', models.FileField(upload_to='samples')),
            ],
        ),
    ]
